version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - api-network
    volumes:
      - api-volume:/var/lib/postgresql/data

  redis:
    container_name: redis_container
    image: redis
    env_file:
      - .env
    ports:
      - '6379:6379'
    networks:
      - api-network
    volumes:
      - api-volume:/var/lib/postgresql/data

networks:
  api-network:
    driver: bridge

volumes:
  api-volume:
